# -*- coding: utf-8 -*-
"""IR_praktikum01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qyfIc1x7ik9CDOX3ml1vFCBZ2IbeU0MH
"""

from google.colab import drive
drive.mount('/content/gdrive')

path = "/content/gdrive/MyDrive/InformationRetrieval/praktikum01"

import pandas as pd
df = pd.read_xml(path + '/data/kompas-beritaPart1.xml')

df.head()

# Mencari Informasi Data
df.info()

# Memeriksa Nilai Nan dan Duplikat
df.isnull().sum()

# Case Folding (Mengubah huruf kapital menjadi huruf kecil)
def caseFolding(text):
  text = text.lower()
  return text

# memastikan Bahwa function yg dibuat sudah bekerja dengan baik
contoh = "Terima Kasih, KAK! Kamu Sangat Baik Sekali Kepadaku Hari Ini."
print(f'original:{contoh}')
print(f'case folded: {caseFolding(contoh)}')

# Punctuation Removal
import re

def punctuationRemoval(text):
  text = re.sub(r'[^\w\s]', '', text)
  return text

# Memastikan Punctuation Removal
contoh = "Terima Kasih, KAK..! Kamu sangat baik sekali hari inii!!!."
print(f'original: {contoh}')
print(f'punctuation removed: {punctuationRemoval(contoh)}')

# Penerapan Function
df['clean'] = df['isi'].apply(caseFolding)
df['clean'] = df['clean'].apply(punctuationRemoval)
df.head()

# Membuat Function Tokenisasi
def tokenize(text):
  return text.split(" ")

contoh = "Terimakasih, KAK!! Kamu sangat baik sekali padaku hari ini."
print(f'original: {contoh}')

clean = caseFolding(contoh)
clean = punctuationRemoval(clean)
print(f'tokenized: {tokenize(clean)}')

# Penerapan Tokenisasi
df['tokens'] = df['clean'].apply(tokenize)
df.head()

# menghitung Frekuensi Kata Menggunakan library collection dan funstion counter
from collections import Counter

all_token = []
for tokens in df['tokens']:
  for token in tokens:
    all_token.append(token)

tf = Counter(all_token)
tf_df = pd.DataFrame(tf.items(), columns=['term', 'freq'])
tf_df_sorted = tf_df.sort_values(by='freq', ascending=False)
tf_df_sorted.head()

# membuat kolom baru 'rank'
tf_df_sorted['rank'] = tf_df_sorted['freq'].rank(method='first', ascending=False).astype(int)
tf_df_sorted.head()

tf_df.columns

tf_df.columns = ['Term', 'Frequency']

tf_df['Rank'] = tf_df['Frequency'].rank(method='first', ascending=False).astype(int)
tf_sorted_rank = tf_df.sort_values(by='Rank', ascending=True)
tf_sorted_rank.head(20)

# Menghitung Nilai k = f x r Untuk Setiap Kata Term
tf_df_sorted['k=f*r'] = tf_df_sorted['freq'] * tf_df_sorted['rank']
tf_df_sorted.head(n=100)

# Visualisasi Menggunakan Library Matplotlib
import matplotlib.pyplot as plt

rank = tf_df_sorted['rank']
freq = tf_df_sorted['freq']
plt.figure(figsize=(10, 5))
plt.scatter(rank, freq, color='red', s=10)
plt.title("Term Frequency vs Rank")
plt.xlabel("rank")
plt.ylabel("frequensi (f)")

plt.grid(True)
plt.show()

